scan_filter_chain:
  ros__parameters:
    filter1:
      name: chassis_box_filter
      type: laser_filters/LaserScanBoxFilter
      params:
        box_frame: base_footprint
        # Box dimensions (meters) centered on base_footprint
        max_x:  0.12   # Forward
        min_x: -0.12   # Backward
        max_y:  0.10   # Left
        min_y: -0.10   # Right
        max_z:  0.50   # Up
        min_z: -0.10   # Down
